[package]
name = "pugl-ui"
version = "0.1.0"
authors = ["Johannes Mueller <github@johannes-mueller.org>"]
edition = "2018"

[dependencies]
cairo-rs = "0.8.1"
pango = "0.8.0"
pangocairo = "0.9.0"
downcast-rs = "1.1.1"

pugl-sys = { git = "http://github.com/johannes-mueller/pugl-sys" }
